name: changedetection

services:
    changedetection.io:
        image: dgtlmoon/changedetection.io
        container_name: changedetection.io
        restart: unless-stopped
        ports:
            - 127.0.0.1:5000:5000
        volumes:
            - datastore-volume:/datastore
volumes:
    datastore-volume:
        external: true
        name: datastore-volume