name: mealie

services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v2.6.0
    container_name: mealie

    restart: uless-stopped
    ports:
        - "9925:9000" 
    deploy:
      resources:
        limits:
          memory: 1000M  
    volumes:
      - mealie-data:/app/data/
    networks:
      - homelab_default
    environment:
      ALLOW_SIGNUP: "true"
      PUID: 1000
      PGID: 1000
      TZ: Europe/Berlin
      BASE_URL: https://mealie.yourdomain.com

volumes:
  mealie-data:

networks:
  homelab_default:
    external: true