services:
  navidrome:
    image: deluan/navidrome:latest
    #user: 1000:1000 # should be owner of volumes
    container_name: navidrome
    restart: unless-stopped
    environment:
      ND_PORT: "4533" # Http port
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
    volumes:
      - "/home/user/navidrome/data:/data"
      - "/home/user/navidrome/music:/music:ro"
    networks:
      - "homelab_default"
      
networks:
  homelab_default:
    external: true