name: nextcloud

services:
    nextcloud:
        image: "lscr.io/linuxserver/nextcloud:latest"
        container_name: "nextcloud"
        restart: "unless-stopped"
        environment:
            - "PUID=1000"
            - "PGID=1000"
            - "TZ=Europe/Berlin"
        volumes:
            - "./nextcloud/appdata:/config"
            - "./nextcloud/data:/data"